name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.0, 8.1, 8.2, 8.3, 8.4]
        laravel: [9.*, 10.*, 11.*, 12.*]
        include:
          - php: 8.0
            laravel: 9.*
          - php: 8.1
            laravel: 9.*
          - php: 8.1
            laravel: 10.*
          - php: 8.2
            laravel: 10.*
          - php: 8.3
            laravel: 10.*
          - php: 8.2
            laravel: 11.*
          - php: 8.3
            laravel: 11.*
          - php: 8.4
            laravel: 11.*
          - php: 8.2
            laravel: 12.*
          - php: 8.3
            laravel: 12.*
          - php: 8.4
            laravel: 12.*

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, intl, json
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: composer test 